### ISSUE TITLE
🚀 Feature: Support for self hosted Sentry

### ISSUE THREAD

**Issue by maximilianmaihoefner** [utopia-php/logger#6]
### 🔖 Feature description

Sentry can be [self hosted](https://github.com/getsentry/self-hosted), so it would be nice if we could specify the Host instead of having it [hardcoded](https://github.com/utopia-php/logger/blob/main/src/Logger/Adapter/Sentry.php#L85) to`https://sentry.io/api`.

### 🎤 Pitch

This would allow users of self hosted sentry instances to also use the Utopia Logger by allowing `sentryHost` to be passed into the SentryAdapter the same way `projectId` and `sentryKey` are.

In Appwrite we could append/prepend it to the `_APP_LOGGING_CONFIG` and if it's missing default to `sentry.io`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by maximilianmaihoefner** [comment]
If you like I can try creating a PR for this, but I am not really a PHP-Developer, to it might be more work to review my mess then to have it implemented by someone how knows what they are doing.

**Comment by eldadfux** [comment]
@maximilianmaihoefner you can ahead with a PR, our team can help if required.

**Comment by Meldiron** [comment]
Thanks for the PR 🥳 We have merged your PR, so I am closing this issue.
